### ISSUE TITLE
Datetime fields are returned in non readable format

### ISSUE THREAD

**Issue by kovinet** [nchizhov/inok-dbf#3]
I have a DBF file, and when looping trough records when outputting value of DATETIME field in DBF I get following value `�m%x([` or `By%��\` as two examples.

I am not sure how can I convert this to some meaningful date time format.

**Comment by nchizhov** [comment]
May you say version of DBF-file?

And, maybe, dbf-file (or part of dbf-file)?

**Comment by kovinet** [comment]
According to Header info, the version is 48.

Column info is this:

```
array:9 [
    "name" => "tcreated"
    "type" => "T"
    "length" => 8
    "decimal" => 0
    "flag" => 4
    "system" => false
    "has_null" => false
    "binary" => true
    "auto_increment" => false
  ]

```
Data is binary. I could manually unpack it, but I don't know what kind of format could it be. If I use `unpack('L', $record)` then I get interger, for example `2458600` which is too short to be Unix Timestamp. So I don't know how to convert it to date... Original string is like this:  `b"èƒ%\x00Ç˜`\x02"`

**Comment by nchizhov** [comment]
This will be fixed soon - about 2-3 days

**Comment by nchizhov** [comment]
Fixed. You may check

**Comment by kovinet** [comment]
Hi. Your latest commit did partially solve the issue, but there is still a problem which produces exception. I have run it on test DB, it parses some dates and then it throws en error: `ErrorException  : unpack(): Type L: not enough input, need 4, have 3`

Error is at line 122 of Records.php

```
$timeData = unpack("L", substr($data, 4, 4))[1];
```

I have solved it by wrapping the line in try catch for now...

**Comment by nchizhov** [comment]
May you give me your test DB? On my test DBs DateTime fields was encoded correctly

I'm now on holidays, will be back in 2 weeks.

**Comment by kovinet** [comment]
It's not really test DB, it contains private info so I can't send it. There is a problem with time part of dates in some cases, with try and catch and setting time to 000000 is fine for my use case. I can create pull request for this if you wish.

Thank you and enjoy your holiday. :-)

**Comment by nchizhov** [comment]
May you paste here description of this field? It it return size of field - 8? 

By standard of Visula FoxPro DateTime field is always 8 bytes. (4 bytes date and 4 bytes time)

**Comment by kovinet** [comment]
There is still a bug in the code somewhere, as mentioned before I am getting only 7 bytes of data for DateTime somehow. So when it is split in 2 parts with substr, where first part is date part and second part is time part - second part has sometimes only length equal to 3, not 4, so unpack throws error.

I have tried parsing same file (VisualFoxPro) with some other libs and dates come out fine. Also here they do in like 95% but remaining 5% throws error. I am guessing bug is not in function where binary string is converted to DateTime, but before where row is split to chunks and this field is somehow 1 byte too short.

**Comment by nchizhov** [comment]
May you give me dbf-file with error (maybe part of file) ?

**Comment by nchizhov** [comment]
> There is still a bug in the code somewhere, as mentioned before I am getting only 7 bytes of data for DateTime somehow. So when it is split in 2 parts with substr, where first part is date part and second part is time part - second part has sometimes only length equal to 3, not 4, so unpack throws error.
> 
> I have tried parsing same file (VisualFoxPro) with some other libs and dates come out fine. Also here they do in like 95% but remaining 5% throws error. I am guessing bug is not in function where binary string is converted to DateTime, but before where row is split to chunks and this field is somehow 1 byte too short.

May you give me dbf-file with error (maybe part of file) ? And version of dbf-file

**Comment by kovinet** [comment]
It is big file with personal information, so I can not share it. I tried to fix it myself but couldn't find a bug so I ended up using another library instead of this one.

I will try to obfuscate the personal data and extract only problematic rows and send it to you.

Version of file is 48

**Comment by kovinet** [comment]
You can download test file [here](https://www.dropbox.com/s/erk7l02032gelyj/todoterm3.dbf?dl=0) 

It reads couple of records and then throws an error:

> In Records.php line 122:
>                                                       
>   unpack(): Type L: not enough input, need 4, have 3  

As encoding for iconv you have to set 'utf-8//IGNORE', else there are also encoding related errors.

**Comment by nchizhov** [comment]
> You can download test file [here](https://www.dropbox.com/s/erk7l02032gelyj/todoterm3.dbf?dl=0)
> 
> It reads couple of records and then throws an error:
> 
> > In Records.php line 122:
> > unpack(): Type L: not enough input, need 4, have 3
> 
> As encoding for iconv you have to set 'utf-8//IGNORE', else there are also encoding related errors.

Thank you for sample file.
I found bug in my code and fixed it. Please check with new version.
